remote_theme: pmarsceill/just-the-docs

logo: "/imgs/logo.png"

# Footer content appears at the bottom of every page's main content
footer_content: "Copyright &copy; 2024 RPM Hub. Distributed by CC-BY-4.0 license"